### PR TITLE
fix: stop page from refreshing everytime route changes

### LINKED ISSUE #68: Dashboard does not work in mobile view
Image

### PR DESCRIPTION
**Pull request by arunanshub**
closes #68, #91

### CODE REVIEW

File: src/components/ui/sidebar.tsx [hunk 1]
```diff
@@ -19,7 +19,7 @@ import {
   TooltipTrigger,
 } from "@/components/ui/tooltip";
 
-const SIDEBAR_COOKIE_NAME = "sidebar:state";
+const SIDEBAR_COOKIE_NAME = "sidebar_state";
```
Comment (abhisek) [inline src/components/ui/sidebar.tsx:22]: Why are we changing this? This is `shadcn` component and I am guessing it has a certain level of maturity?

File: tailwind.config.ts [hunk 2]
```diff
@@ -80,6 +90,6 @@ export default {
         "accordion-up": "accordion-up 0.2s ease-out",
       },
     },
-    plugins: [tailwindcssAnimate],
+    plugins: ["tailwindcssAnimate"],
```
Comment (abhisek) [inline tailwind.config.ts:93]: Any reference for this change? What does it solve?

File: src/app/globals.css [hunk 3]
```diff
@@ -88,3 +88,12 @@ body {
     @apply bg-background text-foreground;
   }
 }
+
+@layer base {
```
Comment (abhisek) [inline src/app/globals.css:92]: Whats the objective of this global change?

File: src/components/ui/sidebar.tsx (hunk 1 above)
Comment (arunanshub) [reply src/components/ui/sidebar.tsx:22]: Yes i've just updated it from shadcn's upstream itself.

File: tailwind.config.ts [hunk 4]
```diff
@@ -51,6 +51,16 @@ export default {
           "4": "hsl(var(--chart-4))",
           "5": "hsl(var(--chart-5))",
         },
+        sidebar: {
```
Comment (abhisek) [inline tailwind.config.ts:54]: @arunanshub Is this added by `shadcn` or a manual change? Whats the reason of this change if manual?

File: src/app/globals.css [hunk 5]
```diff
@@ -81,9 +81,8 @@ body {
 
 @layer base {
   * {
-    @apply border-border;
+    @apply border-border outline-ring/50;
```
Comment (abhisek) [inline src/app/globals.css:84]: Why is this required? I am a bit defensive about making changes that has global impact

Comment (arunanshub) [reply src/app/globals.css:84]: all the changes are from shadcn itself. My rationale was that since we're following shadcn, so updates from upstream won't hurt. Let me know if I should remove it.

image

File: tailwind.config.ts (hunk 4 above)
Comment (arunanshub) [reply tailwind.config.ts:54]: shadcn. This is the styling for sidebar. without it sidebar would look transparent in mobile view.
